version: 2
jobs:
  build:
    working_directory: ~/grow
    docker:
      - image: grow/base:latest
    steps:
      - checkout

      - run:
          name: Install Packages
          command: "apt-get update && apt-get install -y libfontconfig"

      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: Firebase Install
          command: yarn global add firebase-tools

      - run:
          name: Grow Install
          command: grow install

      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
            - /usr/local/share/.cache/yarn/v1

      - run:
          name: Firebase Production
          command: 'if [ "${TRAVIS_BRANCH}" = "production" ]; then firebase use production; fi'

      - run:
          name: Firebase Staging
          command: firebase use staging
          # command: 'if [ "${TRAVIS_BRANCH}" = "master" ]; then firebase use staging; fi'

      - run:
          name: Production Firebase
          command: 'if [ "${TRAVIS_BRANCH}" = "production" ]; then firebase use production; fi'

      - run:
          name: Grow Build
          command: grow build

      - run:
          name: Deploy
          command: firebase deploy --token "$FIREBASE_TOKEN" --non-interactive

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      # - build:
      #     filters:
      #       branches:
      #         only:
      #         - production
      #         - master
